# Generated by Django 5.0.6 on 2025-10-07 03:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Información de la empresa', 'verbose_name_plural': 'Quiénes Somos'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Información de contacto', 'verbose_name_plural': 'Información de contacto'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Imagen de galería', 'verbose_name_plural': 'Galería de imágenes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(verbose_name='Descripción / Historia / Misión de la empresa'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título principal'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título de la imagen'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Imagen del servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del servicio'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del video'),
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Imagen de la empresa')),
                ('caption', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción de la imagen (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.aboutus', verbose_name='Sección relacionada')),
            ],
            options={
                'verbose_name': 'Imagen de Quiénes Somos',
                'verbose_name_plural': 'Imágenes de Quiénes Somos',
                'ordering': ['-created_at'],
            },
        ),
    ]
