# Generated by Django 5.0.6 on 2025-10-07 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_aboutus_options_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo o función')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Foto del miembro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='web.aboutus', verbose_name='Empresa relacionada')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Equipo de trabajo',
                'ordering': ['name'],
            },
        ),
    ]
