# Generated by Django 5.0.6 on 2025-10-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='budgets/', verbose_name='Imagen opcional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de presupuesto',
                'verbose_name_plural': 'Solicitudes de presupuestos',
                'ordering': ['-created_at'],
            },
        ),
    ]
